name: Deploy to AWS S3
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build frontend
        env:
          REACT_APP_API_BASE_URL: ${{ secrets.EC2_IP }}
        run: CI=false npm run build
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/brad-thee-stallion-portfolio
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Check AWS identity
        run: aws sts get-caller-identity
      
      - name: Upload to S3
        run: |
          aws s3 rm "s3://${{ secrets.AWS_S3_BUCKET_NAME }}" --recursive
          aws s3 cp "${{ github.workspace }}/build/" "s3://${{ secrets.AWS_S3_BUCKET_NAME }}" --recursive

      - name: Add CSP headers to HTML/JS files
        run: |
          CSP_HEADER="default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'"
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET_NAME }}/index.html s3://${{ secrets.AWS_S3_BUCKET_NAME }}/index.html --metadata-directive REPLACE --metadata "Content-Security-Policy=${CSP_HEADER}"
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET_NAME }}/404.html s3://${{ secrets.AWS_S3_BUCKET_NAME }}/404.html --metadata-directive REPLACE --metadata "Content-Security-Policy=${CSP_HEADER}"
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET_NAME }}/static/js/main.8dadc5b5.js s3://${{ secrets.AWS_S3_BUCKET_NAME }}/static/js/main.8dadc5b5.js --metadata-directive REPLACE --metadata "Content-Security-Policy=${CSP_HEADER}"
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET_NAME }}/static/js/453.5858e738.chunk.js s3://${{ secrets.AWS_S3_BUCKET_NAME }}/static/js/453.5858e738.chunk.js --metadata-directive REPLACE --metadata "Content-Security-Policy=${CSP_HEADER}"
